version: "3"
networks:
  default_net:
    driver: bridge
services:
  redis:
    image: redis:alpine
    networks:
      - default_net
    ports:
      - 6379
  db:
    image: mysql:latest
    restart: always
    networks:
      - default_net
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 880622
  dbinit:
    image: mysql:latest
    entrypoint: /bin/bash
    networks:
      - default_net
    volumes:
      - .:/host
    command: -c "sleep 4; mysql -u root --password=880622 -h mysql < /host/init.sql; exit 0"
    depends_on:
      - db
    links:
      - db:mysql
  app:
    build: .
    networks:
      - default_net
    links:
      - redis:redis
      - db:mysql
      - dbinit
    depends_on:
      - db
      - redis
    ports:
      - 8080
